/* XDISPARADORES */

DROP TRIGGER TR_MOD_PERSONA;
DROP TRIGGER TR_ESTADO_ACTIVIDAD;
DROP TRIGGER TR_PART_ACT;
DROP TRIGGER TR_VIGENCIA_SUSCRIPCION;
DROP TRIGGER TR_INSERTSUSCRIPCION;
DROP TRIGGER TR_AUTO_ACTIVIDAD;
DROP TRIGGER TR_AUTO_EVENTOS;
DROP TRIGGER TR_AUTO_ESTUDIANTE;
DROP TRIGGER TR_AUTO_SUSCRIPCION;
DROP TRIGGER TR_AUTO_SUSCRIPCION2;
DROP TRIGGER TR_AUTO_NOTICIA;
DROP TRIGGER TR_AUTO_COMENTARIO_NOTICIA;