--XTABLAS--
DROP TABLE Persona CASCADE CONSTRAINTS;
DROP TABLE Profesor CASCADE CONSTRAINTS;
DROP TABLE Curso CASCADE CONSTRAINTS;
DROP TABLE Curso_Profesor CASCADE CONSTRAINTS;
DROP TABLE Estudiante CASCADE CONSTRAINTS;
DROP TABLE Directivo CASCADE CONSTRAINTS;
DROP TABLE Personal_Ad CASCADE CONSTRAINTS;
DROP TABLE Telefonos_Persona CASCADE CONSTRAINTS;
DROP TABLE Noticia CASCADE CONSTRAINTS;
DROP TABLE Comentario_Noticia CASCADE CONSTRAINTS;
DROP TABLE Actividad CASCADE CONSTRAINTS;
DROP TABLE Suscripcion CASCADE CONSTRAINTS;
DROP TABLE Comentario_actividad CASCADE CONSTRAINTS;
DROP TABLE Evento CASCADE CONSTRAINTS;


