--PRIMARIAS--

ALTER TABLE Persona ADD CONSTRAINT PK_PERSONA PRIMARY KEY(tid,nid);
ALTER TABLE Telefonos_Persona ADD CONSTRAINT PK_TELEFONOS_PERSONA PRIMARY KEY(tid,nid, telefono);
ALTER TABLE Profesor ADD CONSTRAINT PK_PROFESOR PRIMARY KEY(tid,nid);
ALTER TABLE Curso ADD CONSTRAINT PK_CURSO PRIMARY KEY(id_curso);
ALTER TABLE Curso_Profesor ADD CONSTRAINT PK_CURSO_PROFESOR PRIMARY KEY(tid,nid,curso);
ALTER TABLE Estudiante ADD CONSTRAINT PK_ESTUDIANTE PRIMARY KEY(tid,nid);
ALTER TABLE Directivo ADD CONSTRAINT PK_DIRECTIVO PRIMARY KEY(tid,nid);
ALTER TABLE Personal_Ad ADD CONSTRAINT PK_PERSONAL PRIMARY KEY(tid,nid);
ALTER TABLE Noticia ADD CONSTRAINT PK_NOTICIA PRIMARY KEY(id_noticia);
ALTER TABLE Comentario_Noticia ADD CONSTRAINT PK_COMENTARIO_NOTICIA PRIMARY KEY(noticia, tid, nid, detalle);
ALTER TABLE Evento ADD CONSTRAINT PK_EVENTO PRIMARY KEY(id_evento);
ALTER TABLE Actividad ADD CONSTRAINT PK_ACTIVIDAD PRIMARY KEY(evento);
ALTER TABLE Suscripcion ADD CONSTRAINT PK_SUSCRIPCION PRIMARY KEY(tid, nid, actividad, idSolicitud);
ALTER TABLE Comentario_actividad ADD CONSTRAINT PK_COMENTARIO_ACTIVIDAD PRIMARY KEY(actividad, tid, nid, detalle);


