--CLAVES FORANEAS--

ALTER TABLE Profesor ADD CONSTRAINT FK_PROFESOR_PERSONA FOREIGN KEY(tid,nid) REFERENCES Persona(tid, nid);

ALTER TABLE Curso_Profesor ADD CONSTRAINT FK_CURSO_PROFESOR1 FOREIGN KEY(tid, nid) REFERENCES Profesor(tid, nid);
ALTER TABLE Curso_Profesor ADD CONSTRAINT FK_CURSO_PROFESOR2 FOREIGN KEY(curso) REFERENCES Curso(id_curso);

ALTER TABLE Estudiante ADD CONSTRAINT FK_ESTUDIANTE_PERSONA FOREIGN KEY(tid,nid) REFERENCES Persona(tid,nid);
ALTER TABLE Directivo ADD CONSTRAINT FK_DIRECTIVO_PERSONA FOREIGN KEY(tid,nid) REFERENCES Persona(tid,nid);
ALTER TABLE Personal_Ad ADD CONSTRAINT FK_PERSONAL_PERSONAL_AD FOREIGN KEY(tid,nid) REFERENCES Persona(tid,nid);
ALTER TABLE Telefonos_Persona ADD CONSTRAINT FK_TELEFONOS_PERSONA FOREIGN KEY(tid, nid) REFERENCES Persona(tid, nid);

ALTER TABLE Comentario_Noticia ADD CONSTRAINT FK_COMENTARIO_NOTICIA1 FOREIGN KEY(noticia) REFERENCES Noticia(id_noticia);
ALTER TABLE Comentario_Noticia ADD CONSTRAINT FK_COMENTARIO_NOTICIA2 FOREIGN KEY(tid, nid) REFERENCES Persona(tid,nid);
ALTER TABLE Comentario_Noticia ADD CONSTRAINT FK_COMENTARIO_NOTICIA3 FOREIGN KEY (noticia, tid, nid, detalle) REFERENCES Comentario_Noticia(noticia, tid, nid, detalle);

ALTER TABLE Comentario_actividad ADD CONSTRAINT FK_COMENTARIO_ACTIVIDAD1 FOREIGN KEY(actividad) REFERENCES Actividad(evento);
ALTER TABLE Comentario_actividad ADD CONSTRAINT FK_COMENTARIO_ACTIVIDAD2 FOREIGN KEY(tid, nid) REFERENCES Persona(tid,nid);
ALTER TABLE Comentario_actividad ADD CONSTRAINT FK_COMENTARIO_ACTIVIDAD3 FOREIGN KEY(actividad, tid, nid, detalle) REFERENCES Comentario_Actividad(actividad, tid, nid, detalle);

ALTER TABLE Actividad ADD CONSTRAINT FK_ACTIVIDAD FOREIGN KEY(evento) REFERENCES Evento(id_evento);

ALTER TABLE Suscripcion ADD CONSTRAINT FK_SUSCRIPCION1 FOREIGN KEY(actividad) REFERENCES Actividad(evento);
ALTER TABLE Suscripcion ADD CONSTRAINT FK_SUSCRIPCION2 FOREIGN KEY(tid, nid) REFERENCES Persona(tid,nid);



