--ACCIONES--

ALTER TABLE Directivo DROP CONSTRAINT FK_DIRECTIVO_PERSONA;
ALTER TABLE Directivo ADD CONSTRAINT FK_DIRECTIVO_PERSONA FOREIGN KEY(tid,nid) REFERENCES Persona(tid,nid)ON DELETE CASCADE;

ALTER TABLE Telefonos_Persona DROP CONSTRAINT FK_TELEFONOS_PERSONA;
ALTER TABLE Telefonos_Persona ADD CONSTRAINT FK_TELEFONOS_PERSONA FOREIGN KEY(tid, nid) REFERENCES Persona(tid, nid)ON DELETE CASCADE;

ALTER TABLE Servicios_Binestar DROP CONSTRAINT FK_SERVICIO_PERSONA;
ALTER TABLE Servicios_Binestar ADD CONSTRAINT FK_SERVICIO_PERSONA FOREIGN KEY(tid, nid) REFERENCES Persona(tid, nid)ON DELETE CASCADE;

ALTER TABLE Clubes_Grupos DROP CONSTRAINT FK_CLUB_PERSONA;
ALTER TABLE Clubes_Grupos ADD CONSTRAINT FK_CLUB_PERSONA FOREIGN KEY(codigo_representante) REFERENCES Persona(codigo)ON DELETE CASCADE;

ALTER TABLE Clubes_Grupos DROP CONSTRAINT FK_CLUB_SERVICIOS;
ALTER TABLE Clubes_Grupos ADD CONSTRAINT FK_CLUB_SERVICIOS FOREIGN KEY(id_servicio) REFERENCES Servicios_Binestar(id_servicio)ON DELETE CASCADE;

ALTER TABLE Solicitudes DROP CONSTRAINT FK_SOL_SERVICIOS;
ALTER TABLE Solicitudes ADD CONSTRAINT FK_SOL_SERVICIOS FOREIGN KEY(id_servicio) REFERENCES Servicios_Binestar(id_servicio)ON DELETE CASCADE;

ALTER TABLE Evento DROP CONSTRAINT FK_EVENTO_PERSONA;
ALTER TABLE Evento ADD CONSTRAINT FK_EVENTO_PERSONA FOREIGN KEY(nid, tid) REFERENCES Persona(nid, tid)ON DELETE CASCADE;

ALTER TABLE Encuestas DROP CONSTRAINT FK_ENCUESTAS_EVENTO;
ALTER TABLE Encuestas ADD CONSTRAINT FK_ENCUESTAS_EVENTO FOREIGN KEY(evento) REFERENCES Evento(id_evento)ON DELETE CASCADE;

--No es posible borrar la pregunta con la FOREIGN key de encuesta
ALTER TABLE Preguntas DROP CONSTRAINT FK_PREG_ENCUESTA;
ALTER TABLE Preguntas ADD CONSTRAINT FK_PREG_ENCUESTA FOREIGN KEY(encuesta) REFERENCES Encuestas(id_encuesta)ON DELETE CASCADE;
