--PRIMARIAS--

ALTER TABLE Persona ADD CONSTRAINT PK_PERSONA PRIMARY KEY(tid,nid);
ALTER TABLE Telefonos_Persona ADD CONSTRAINT PK_TELEFONOS_PERSONA PRIMARY KEY(tid,nid, telefono);
ALTER TABLE Directivo ADD CONSTRAINT PK_DIRECTIVO PRIMARY KEY(tid,nid);
ALTER TABLE Evento ADD CONSTRAINT PK_EVENTO PRIMARY KEY(id_evento);
ALTER TABLE Servicios_Binestar ADD CONSTRAINT PK_SERVICIOS PRIMARY KEY(id_servicio);
ALTER TABLE Clubes_Grupos ADD CONSTRAINT PK_CLUBES PRIMARY KEY(id_club);
ALTER TABLE Solicitudes ADD CONSTRAINT PK_SOL PRIMARY KEY(id_solicitud);
ALTER TABLE Encuestas ADD CONSTRAINT PK_ENCUESTAS PRIMARY KEY(id_encuesta);
ALTER TABLE Preguntas ADD CONSTRAINT PK_PREG PRIMARY KEY(encuesta, detalle);


