--CLAVES FORANEAS--

ALTER TABLE Directivo ADD CONSTRAINT FK_DIRECTIVO_PERSONA FOREIGN KEY(tid,nid) REFERENCES Persona(tid,nid);
ALTER TABLE Telefonos_Persona ADD CONSTRAINT FK_TELEFONOS_PERSONA FOREIGN KEY(tid, nid) REFERENCES Persona(tid, nid);

ALTER TABLE Servicios_Binestar ADD CONSTRAINT FK_SERVICIO_PERSONA FOREIGN KEY(tid, nid) REFERENCES Persona(tid, nid);

ALTER TABLE Clubes_Grupos ADD CONSTRAINT FK_CLUB_PERSONA FOREIGN KEY(codigo_representante) REFERENCES Persona(codigo);
ALTER TABLE Clubes_Grupos ADD CONSTRAINT FK_CLUB_SERVICIOS FOREIGN KEY(id_servicio) REFERENCES Servicios_Binestar(id_servicio);

ALTER TABLE Solicitudes ADD CONSTRAINT FK_SOL_SERVICIOS FOREIGN KEY(id_servicio) REFERENCES Servicios_Binestar(id_servicio);

ALTER TABLE Evento ADD CONSTRAINT FK_EVENTO_PERSONA FOREIGN KEY(nid, tid) REFERENCES Persona(nid, tid);

ALTER TABLE Encuestas ADD CONSTRAINT FK_ENCUESTAS_EVENTO FOREIGN KEY(evento) REFERENCES Evento(id_evento);

ALTER TABLE Preguntas ADD CONSTRAINT FK_PREG_ENCUESTA FOREIGN KEY(encuesta) REFERENCES Encuestas(id_encuesta);