--XDISPARADORES--

DROP TRIGGER TR_MOD_PERSONA;

DROP TRIGGER TR_AUTO_EVENTOS;

DROP TRIGGER TR_AUTO_EST_SOLICITUD;

DROP TRIGGER TR_AUTO_EST_ENCUESTA;

DROP TRIGGER TR_MODIFICAR_ESTADO_PREGUNTAS;

DROP TRIGGER TR_VIGENCIA_SOLICITUD;

DROP TRIGGER TR_ELIMINAR_ENCUESTAS;
