--xTABLAS--

DROP TABLE Persona CASCADE CONSTRAINTS;
DROP TABLE Directivo CASCADE CONSTRAINTS;
DROP TABLE Telefonos_Persona CASCADE CONSTRAINTS;
DROP TABLE Evento CASCADE CONSTRAINTS;
DROP TABLE Servicios_Binestar CASCADE CONSTRAINTS;
DROP TABLE Clubes_Grupos CASCADE CONSTRAINTS;
DROP TABLE Solicitudes CASCADE CONSTRAINTS;
DROP TABLE Encuestas CASCADE CONSTRAINTS;
DROP TABLE Preguntas CASCADE CONSTRAINTS;
